name: HTTP Health Checker

on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *" # Run every midnight

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      - name: Checking HTTP status codes are valid
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["https://www.sadikkuzu.com", "https://sadikkuzu.com"]'
          expected: '[301, 200]'
